services:
  backend:
    build:
      context: ./flask_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./flask_backend/app/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: